In [50]:
import groebner_class, multi_power, multi_cheb
from multi_cheb import MultiCheb
from multi_power import MultiPower
from maxheap import Term
import numpy as np
from scipy.linalg import lu


%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [4]:
A = MultiCheb(np.array([[1,1],[2,3]]))
B = MultiCheb(np.array([[1,1],[3,4]]))
C = MultiCheb(np.array([[5,2],[2,4]]))
#D = multi_cheb.MultiCheb(np.array([[1,1,1],[2,2,2],[3,3,3]]))

In [6]:
grob = groebner_class.Groebner([A,B,C])
grob.add_s_to_matrix()
print(grob.np_matrix)
grob.calc_s(A,B).coeff

AttributeError: module 'maxheap' has no attribute 'TermOrder'

In [7]:
print([i.val for i in grob.matrix_terms])
print(grob.np_matrix)

NameError: name 'grob' is not defined

In [8]:
grob.add_r_to_matrix()
grob.np_matrix = grob.np_matrix.loc[:, (grob.matrix != 0).any(axis=0)]
print(grob.matrix)

# Reorder correctly
ord_mat = grob.np_matrix[['[2 2]', '[2 1]', '[1 2]', '[2 0]', '[1 1]', '[0 2]','[1 0]', '[0 1]', '[0 0]']]
grob_mat = ord_mat.values

new_mat_index = ord_mat.columns.values

new_mat = np.vstack((grob_mat[3:], grob_mat[:3])) # Put R on top for reduction

P,L,U = lu(new_mat)
P_argmax = np.argmax(P,axis=0)

print(U[-6:])

NameError: name 'grob' is not defined

In [9]:
import numpy as np
T = np.random.rand( 4, 3, 5, 2 )
np.allclose( T.flatten( )[ ::-1 ].reshape( T.shape ) , T[ ::-1, ::-1, ::-1, ::-1 ] )

True

In [51]:
f1 = MultiPower(np.array([[0,-1.5,.5,],[-1.5,1.5,0],[1,0,0,]]))
f2 = MultiPower(np.array([[0,0,0],[-1,0,1],[0,0,0]]))
f3 = MultiPower(np.array([[0,-1,0,1],[0,0,0,0],[0,0,0,0],[0,0,0,0]]))

In [52]:
print(f1.coeff)
print(f2.coeff)
print(f3.coeff)

[[ 0.  -1.5  0.5]
 [-1.5  1.5  0. ]
 [ 1.   0.   0. ]]
[[ 0  0  0]
 [-1  0  1]
 [ 0  0  0]]
[[ 0 -1  0  1]
 [ 0  0  0  0]
 [ 0  0  0  0]
 [ 0  0  0  0]]


In [53]:
poly_list = [f1, f2, f3]

In [70]:
from vector_space import VectorSpace
vs = VectorSpace()

In [71]:
print(vs.makeBasis(poly_list))

[(0, 0), (0, 1), (0, 2), (1, 0), (1, 1)]


In [56]:
from itertools import product

In [64]:
for i in vs.makeBasis(poly_list): print(i)

(0, 0)
(0, 1)
(0, 2)
(1, 0)
(1, 1)
(1, 2)


In [67]:
any(np.subtract((1,0),(1,2)) < 0)

True

In [30]:
m1 = set(np.linalg.eigvals([[0,0,0,1],[1,0,0,0],[0,1,0,0],[0,0,1,0]]))
my = set(np.linalg.eigvals([[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]]))
mx = set(np.linalg.eigvals([[0,0,1,0],[0,0,0,1],[1,0,0,0],[0,1,0,0]]))
mxy = set(np.linalg.eigvals([[0,1,0,0],[0,0,1,0],[0,0,0,1],[1,0,0,0]]))

In [34]:
roots = intersection(m1, my, mx, mxy)

In [37]:
print(m1)
print(my)
print(mx)
print(mxy)

{(8.3266726846886741e-17+0.99999999999999956j), (0.99999999999999989+0j), (8.3266726846886741e-17-0.99999999999999956j), (-1.0000000000000004+0j)}
{1.0}
{1.0, -1.0}
{(8.3266726846886741e-17+0.99999999999999956j), (0.99999999999999989+0j), (8.3266726846886741e-17-0.99999999999999956j), (-1.0000000000000004+0j)}


In [45]:
mon_1 = np.zeros((3,3,3))
mon_1[0,0,0] = 1
mon_x = np.zeros((3,3,3))
mon_x[1,0,0] = 1
mon_y = np.zeros((3,3,3))
mon_y[0,1,0] = 1
mon_xy = np.zeros((3,3,3))
mon_xy[1,1,0] = 1
mon_z = np.zeros((3,3,3))
mon_z[0,0,1] = 1
mon_z2 = np.zeros((3,3,3))
mon_z2[0,0,2] = 1
mon_xz = np.zeros((3,3,3))
mon_xz[1,0,1] = 1
mon_yz = np.zeros((3,3,3))
mon_yz[0,1,1] = 1

In [48]:
from multi_power import MultiPower
basis = [MultiPower(mon_1), MultiPower(mon_x), MultiPower(mon_y), MultiPower(mon_xy), 
         MultiPower(mon_z), MultiPower(mon_z2), MultiPower(mon_xz), MultiPower(mon_yz)]

In [ ]:
def getOperatorMatrix(poly, basis):
    for monomial in basis:
        